### ISSUE TITLE
Quick question on calc of grad norm in code

### ISSUE THREAD

**Issue by evanatyourservice** [muellerm-95/SAM-BN#1]
Hello! Thank you for a very interesting paper. I have a quick question on [this line](https://github.com/mueller-mp/SAM-ON/blob/73c12021b41dd33ea13caf63f5441c65a99f7103/sam_on.py#L48), I'm wondering why only the norm of perturbed layers is used instead of the norm of the entire gradient like in SAM/ASAM?

**Comment by evanatyourservice** [comment]
To clarify, because of [this line](https://github.com/mueller-mp/SAM-ON/blob/73c12021b41dd33ea13caf63f5441c65a99f7103/sam_on.py#L26) it looks like not all layers are getting into the global norm calculation

**Comment by mueller-mp** [comment]
Hi, and thanks for your question! 
In the original SAM / ASAM algorithm, the perturbation $\epsilon$ is computed by perturbing _all_ parameters, and then normalizing with respect to the norm of _all_ of those parameters, such that the overall perturbation is of size $\rho$:
$$\epsilon_{SAM} =\rho\frac{ \nabla_{\text{all}} L } {|| \nabla_{\text{all}} L ||_{2}}$$

For SAM-ON, we perturb _only_ the normalization layers, and if we want to the total perturbation to be of size $\rho$, we also have to normalize _only_ with respect to the normalization layers:

$$\epsilon_{SAMON} =\rho\frac{ \nabla_{\text{norm}} L } {|| \nabla_{\text{norm}} L ||_{2}}$$

If we were to use the norm of the gradients of all layers, but only perturb the normalization layers, then the total perturbation would be smaller than $\rho$.
Does this make sense?

**Comment by evanatyourservice** [comment]
Ah yes thank you! Excited to try it out. I’m making a jax repo and will link to the paper and this repo
